# Generated by Django 6.0.6 on 2026-06-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_feature_image_alter_testimonial_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('author', models.CharField(default='Partyfiy Team', max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='dashboard_b_created_ed03e9_idx'), models.Index(fields=['is_published'], name='dashboard_b_is_publ_5c30f3_idx')],
            },
        ),
    ]
