# Generated by Django 6.0.6 on 2026-06-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_featurepricing_alter_blogpost_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='billing_period',
        ),
    ]
